144 les evenements et parcours passes s affichent sur le front office
chemins-de-la-transition/semapps pull request #188
Opened 2022-03-30 10:33 UTC by VincentFarcy

Rq : nécessite ce correctif la branche next de semapps : https://github.com/assemblee-virtuelle/semapps/commit/3a7bd283938f810b51af5b6ab17b1a0d93776735

2022-03-30 13:00 UTC, srosset81 requested changes
Super !

2022-03-30 13:00 UTC, srosset81 commented on frontoffice/src/resources/Activity/Event/EventList.js
> +          <UpcomingFilter initialChecked={true} source="http://virtual-assembly.org/ontologies/pair#endDate" label="N'afficher que les événements à venir" />,
`initialChecked={true}` peut être simplifié en `initialChecked`

2022-03-30 14:58 UTC, VincentFarcy commented on frontoffice/src/resources/Activity/Event/EventList.js
> +          <UpcomingFilter initialChecked={true} source="http://virtual-assembly.org/ontologies/pair#endDate" label="N'afficher que les événements à venir" />,
C'est corrigé

2022-03-30 14:59 UTC, VincentFarcy commented on frontoffice/src/commons/UpcomingFilter.js
> +            termType: "Literal",
C'est corrigé

2022-03-31 07:52 UTC, srosset81 approved these changes

2022-03-31 09:05 UTC, merged