227 pouvoir creer des comptes personne et orga a partir du front office
chemins-de-la-transition/semapps pull request #278
Opened 2022-05-30 13:59 UTC by VincentFarcy

Actions de migration à effectuer au moment du déploiement : 
- Import du nouveau type traveler (call importer.types.freshImport) 
- Modifier les droits du container Organization sur le modèle des containers Place, Course, Event (pour ouvrir les droits en écriture aux users autres que traveler)
- Modifier les droits de toutes les ressources de type Organization, Place, Course, Event et Path, dont les droits sont ouverts en écriture à AuthenticatedAgent

```
<https://data.lescheminsdelatransition.org/_acl/organizations#Write>
        a       <http://www.w3.org/ns/auth/acl#Authorization> ;
        <http://www.w3.org/ns/auth/acl#accessTo>
                <https://data.lescheminsdelatransition.org/organizations> ;
        <http://www.w3.org/ns/auth/acl#agentClass>
                <http://www.w3.org/ns/auth/acl#AuthenticatedAgent> ;
        <http://www.w3.org/ns/auth/acl#mode>
                <http://www.w3.org/ns/auth/acl#Write> .
```

En effet un agent authentifié de type "traveler" ne doit pas pouvoir éditer ces ressources

2022-05-31 06:24 UTC, srosset81 requested changes
Merci !
Concernant le problème de permission que tu évoques, il suffit de les définir dans la config `permissions` de chaque container. Ensuite il faut penser à appeler `webacl.resource.refreshContainersPermissions` car c'est cette commande qui va les appliquer.

2022-05-31 06:24 UTC, srosset81 commented on frontoffice/src/commons/lists/CardsList.js
> +      const image = data[id]?.['pair:isDepictedBy'] || data[id]?.['pair:image'];
`pair:image` n'existe pas dans l'ontologie PAIR. C'était utilisé avant que soit introduit `pair:isDepictedBy` (qui a été ensuite changé en `depictedBy`, mais c'est un autre problème), tu l'as trouvé où ?

2022-05-31 06:24 UTC, srosset81 commented on frontoffice/src/layout/UserMenu.js
> +  const TRAVELER_TYPE_URL = useMemo( () => { return process.env.REACT_APP_MIDDLEWARE_URL + 'types/traveler' }, []);
Le `useMemo` n'est pas nécessaire là. `process.env` est défini au moment du build, c'est une constante globale.

2022-05-31 06:24 UTC, srosset81 commented on frontoffice/src/resources/Agent/Actor/Person/PersonEdit.js
> +  const TRAVELER_TYPE_URL = useMemo( () => { return process.env.REACT_APP_MIDDLEWARE_URL + 'types/traveler' }, []);
Même remarque

2022-05-31 06:24 UTC, srosset81 commented on middleware/services/auth.service.js
> +    // webIdSelection: ['nick', 'name', 'familyName'],
Il faut laisser ça, car ça évite que l'adresse mail de l'utilisateur se retrouve dans son webId (comme l'endpoint SPARQL ne vérifie pas les ACL, cela autoriserait n'importe qui à trouver toutes les adresses mail des utilisateurs)

2022-05-31 06:24 UTC, srosset81 commented on middleware/services/auth.service.js
> +          '@context': urlJoin(CONFIG.HOME_URL, 'context.json'),
C'est pas nécessaire de mettre le context car LDP prend par défaut le contexte par défaut (c'est-à-dire le même que tu indiques)

2022-05-31 06:24 UTC, srosset81 commented on middleware/services/auth.service.js
> +          'pair:e-mail': profileData.email,
Non, on ne veut pas enregistrer l'email ! :-) Elle s'enregistre dans le dataset settings.

2022-05-31 06:42 UTC, VincentFarcy commented on frontoffice/src/commons/lists/CardsList.js
> +      const image = data[id]?.['pair:isDepictedBy'] || data[id]?.['pair:image'];
C'est présent dans Person et Organization

2022-05-31 06:53 UTC, srosset81 commented on frontoffice/src/commons/lists/CardsList.js
> +      const image = data[id]?.['pair:isDepictedBy'] || data[id]?.['pair:image'];
Il faudrait le supprimer alors... et peut-être utiliser `pair:depictedBy` partout. Mais ça va demander des migrations, on peut le faire dans une autre PR.

2022-05-31 07:05 UTC, VincentFarcy commented on frontoffice/src/layout/UserMenu.js
> +  const TRAVELER_TYPE_URL = useMemo( () => { return process.env.REACT_APP_MIDDLEWARE_URL + 'types/traveler' }, []);
J'ai enlevé le useMemo.
J'en ai profité pour modifier le isTraveler pour qu'il soit à true par défaut.

2022-05-31 07:05 UTC, VincentFarcy commented on frontoffice/src/resources/Agent/Actor/Person/PersonEdit.js
> +  const TRAVELER_TYPE_URL = useMemo( () => { return process.env.REACT_APP_MIDDLEWARE_URL + 'types/traveler' }, []);
J'ai enlevé le useMemo.
J'en ai profité pour modifier le isTraveler pour qu'il soit à true par défaut.

2022-05-31 07:07 UTC, VincentFarcy commented on middleware/services/auth.service.js
> +    // webIdSelection: ['nick', 'name', 'familyName'],
ok c'est corrigé

2022-05-31 07:14 UTC, VincentFarcy commented on middleware/services/auth.service.js
> +          '@context': urlJoin(CONFIG.HOME_URL, 'context.json'),
ok c'est corrigé

2022-05-31 08:42 UTC, VincentFarcy commented
J'aime autant te passer la main sur cette partie si c'est possible pour toi.
Sinon si tu n'as pas le temps je m'y colle dis moi ;)

2022-05-31 12:05 UTC, srosset81 commented
> J'aime autant te passer la main sur cette partie si c'est possible pour toi. Sinon si tu n'as pas le temps je m'y colle dis moi ;)

Je veux bien que tu le fasses car je crois que tu vois mieux que moi les permissions qu'il s'agit de supprimer.
Et j'ai une masse d'autre choses à faire ;)

2022-05-31 19:55 UTC, VincentFarcy commented
Donc l'idée est de remplacer
```
<http://www.w3.org/ns/auth/acl#agentClass> 
      <http://xmlns.com/foaf/0.1/Agent> et/ou <http://www.w3.org/ns/auth/acl#AuthenticatedAgent>
```
par 	        
```
<http://www.w3.org/ns/auth/acl#agent>
	ressource uri du createur
```

pour les types de ressources : organization, place, event, course, path

Ca te semble ok @srosset81  ?

2022-06-01 14:51 UTC, VincentFarcy commented
C'est ok pour la migration (voir 1er commentaire)

2022-06-01 15:11 UTC, srosset81 approved these changes
Parfait !

2022-06-01 15:12 UTC, merged