309_change_event_fields
chemins-de-la-transition/semapps pull request #310
Opened 2022-06-03 15:51 UTC by clemenceCDLT

2022-06-06 08:47 UTC, srosset81 requested changes
Il y a une confusion entre cdlt:targetAudience (le prédicat) et cdlt:TargetAudience (la classe)
Je note d'ailleurs que la classe cdlt:TargetAudience n'existe pas dans l'ontologie CDLT.

2022-06-06 08:47 UTC, srosset81 commented on backoffice/src/config/dataServers.js
> +        'cdlt:targetAudience': ['/targetAudience'],
Pour être conforme avec le reste des containers, il faut que ce soit au pluriel. Et pour un dossier, je pense que c'est mieux que ce soit avec un tiret: `/target-audiences`
Par ailleurs targetAudience étant une classe, il faut un T majuscule: `'cdlt:TargetAudience'

2022-06-06 08:47 UTC, srosset81 commented on backoffice/src/resources/Concept/TargetAudience/index.js
> +    types: ['cdlt:targetAudience'],
C'est une classe, il faut donc une majuscule: `cdlt:TargetAudience`

2022-06-06 08:47 UTC, srosset81 commented on frontoffice/src/commons/lists/EventsList/NextEvents.js
> +const NextEvents = (props) => {
C'est un détail, mais généralement on préfère faire une destructuration: 
`const NextEvents = ({ similarRecord }) => {`

2022-06-06 08:47 UTC, srosset81 commented on frontoffice/src/config/dataServers.js
> +        'cdlt:targetAudience':['/targetAudience'],
Même commentaire que le premier

2022-06-06 08:47 UTC, srosset81 commented on frontoffice/src/resources/Concept/TargetAudience.js
> +      types: ['cdlt:targetAudience'],
Même remarque que plus haut (T majuscule)

2022-06-06 08:47 UTC, srosset81 commented on middleware/containers.js
> +    acceptedTypes: ['cdlt:targetAudience'],
```js
    path: '/target-audiences',
    acceptedTypes: ['cdlt:TargetAudience'],
```

2022-06-07 16:03 UTC, clemenceCDLT commented
Vignettes événements : Vérifier que le lieu s'affiche si on renseigne seulement une adresse et pas un lieu (j'ai un problème avec LocationInput en local qui m'empêche de tester)

2022-06-09 07:50 UTC, srosset81 commented
> Vignettes événements : Vérifier que le lieu s'affiche si on renseigne seulement une adresse et pas un lieu (j'ai un problème avec LocationInput en local qui m'empêche de tester)

Je comprend pas le lien avec cette PR ?

2022-06-10 13:48 UTC, VincentFarcy commented on middleware/containers.js
> +    acceptedTypes: ['cdlt:targetAudience'],
pris en compte par Clémence

2022-06-10 13:48 UTC, VincentFarcy commented on frontoffice/src/resources/Concept/TargetAudience.js
> +      types: ['cdlt:targetAudience'],
pris en compte par Clémence

2022-06-10 13:48 UTC, VincentFarcy commented on frontoffice/src/config/dataServers.js
> +        'cdlt:targetAudience':['/targetAudience'],
pris en compte par Clémence

2022-06-10 13:48 UTC, VincentFarcy commented on backoffice/src/resources/Concept/TargetAudience/index.js
> +    types: ['cdlt:targetAudience'],
pris en compte par Clémence

2022-06-10 13:48 UTC, VincentFarcy commented on backoffice/src/config/dataServers.js
> +        'cdlt:targetAudience': ['/targetAudience'],
pris en compte par Clémence

2022-06-10 15:42 UTC, VincentFarcy commented on frontoffice/src/commons/lists/EventsList/NextEvents.js
> +const NextEvents = (props) => {
c'est ok

2022-06-10 15:54 UTC, VincentFarcy commented
@clemenceCDLT j'ai effectué la résolution des conflits avec le nouveau master.
Juste quelques points à noter : 
- J'ai mis en commentaire la mise en forme des onglets que tu as codé dans `EventForm`.
Il faudrait l'appliquer sur toutes les ressources pour bien faire. On pourra faire ça tranquillement dans une autre issue.
-  j'ai remplacé le prédicat `cdlt:targetAudience` par `cdlt:hasTargetAudience` / `cdlt:targetAudienceOf`. Il y a une issue pour cela côté ontology https://github.com/chemins-de-la-transition/ontology/issues/12.
- j'ai modifié la valorisation de `perPage` qui posait pb dans `NextEvents` pour `similarEvents`
C'est prêt à merger pour moi.

2022-06-12 14:14 UTC, srosset81 approved these changes
Top !

2022-06-13 07:46 UTC, VincentFarcy commented
J'ai rajouté targetAudience dans Courses comme prévu sur les maquettes Figma

2022-06-13 07:59 UTC, merged