551 fonction publier depublier sur les cleps et pairs
chemins-de-la-transition/semapps pull request #559
Opened 2023-01-05 16:47 UTC by VincentFarcy

2023-02-28 16:29 UTC, srosset81 requested changes
Merci ! C'est du bon boulot, mais il y a quand même quelques petit problèmes de fond à régler à mon avis avant de mettre en prod.

2023-02-28 16:29 UTC, srosset81 commented on frontoffice/src/resources/Agent/Activity/Event/EventForm.js
> +      </FormTab>
Sur le backoffice, lorsqu'on appuie sur le bouton Publier/Dépublier, cela a pour effet d'ajouter ou enlever les droits ACL (via authProvider.addPermission/remotePermission). Ca n'a pas d'impact sur les recherches SPARQL car, pour des raisons de performances, l'endpoint SPARQL ne tient pas compte des WebACL. Mais pour que les données soient cohérentes, cela me semblerait important d'aussi gérer ça sur le frontoffice, lorsqu'une ressource est rendue visible ou invisible. Sinon on risque d'avoir des comportements inattendus.

2023-02-28 16:29 UTC, srosset81 commented on backoffice/src/resources/Place/PlaceList.js
> +          </Datagrid>
Comme le bouton Publier/Dépublier n'est visible que sur la vue "Liste", je crois que ce serait mieux que ce soit la vue par défaut, sinon ça oblige à un clic de plus pour publier un lieu.

2023-05-02 17:18 UTC, srosset81 commented on middleware/services/migration.service.js
> +      }
Noté sur la PR

2023-05-03 08:26 UTC, srosset81 commented on frontoffice/src/resources/Agent/Activity/Event/EventForm.js
> +      </FormTab>
Fait en ajoutant côté backend un PublisherService qui gère ça automatiquement.

2023-05-03 08:52 UTC, srosset81 commented on frontoffice/src/resources/common.js
> +}
OK côté frontoffice tout va être publié par défaut
@GuillaumeAV

2023-05-03 08:56 UTC, GuillaumeAV commented on frontoffice/src/resources/common.js
> +}
Oui en effet, c'est cohérent !

2023-05-09 08:35 UTC, merged